objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Merchandise__c</fullName>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <label>Total Inventory</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestCleanUpBatchClass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestCleanUpBatchClass {

    static testMethod void test() {
        // The query used by the batch job.
		String query = 'SELECT Id,CreatedDate FROM Merchandise__c ' +
		'WHERE Id NOT IN (SELECT Merchandise__c FROM Line_Item__c)';
		
		// Create some test merchandise items to be deleted
		// by the batch job.
		Merchandise__c[] ml = new List<Merchandise__c>();
		for (Integer i=0;i<10;i++) {
		Merchandise__c m = new Merchandise__c(
		Name='Merchandise ' + i,
		Description__c='Some description',
		Price__c=2,
		Inventory__c=100);
		ml.add(m);
		}
		insert ml;
		Test.startTest();
		CleanUpRecords c=new CleanUpRecords(query);
		Database.executeBatch(c);
		Test.stopTest();
		// Verify merchandise items got deleted
		Integer i = [SELECT COUNT() FROM Merchandise__c];
		System.assertEquals(i, 0);
		
		
    }
}